# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true


# Minecraft
minecraft_version=26.1.2

# Yarn mappings
yarn_mappings=26.1.2+build.1


# Fabric
loader_version=0.16.14

fabric_version=0.130.0+26.1


# Mod
mod_version=1.3.0

maven_group=com.breelock.autoclicky

archives_base_name=autoclicky
