# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true


# Fabric Properties
# Minecraft 26.1.2
minecraft_version=26.1.2

# Wird später mit den offiziellen Yarn-Mappings ersetzt
yarn_mappings=26.1.2+build.1

loader_version=0.16.14


# Mod Properties
mod_version=1.3.0
maven_group=com.breelock.autoclicky
archives_base_name=autoclicky


# Dependencies
fabric_version=0.130.0+26.1
